### PR TITLE
Build broken by stray character

### PR DESCRIPTION
**Pull request by lloydwatkin**

### CODE REVIEW

**Comment by dodo** [comment]
nope this is on purpose.

if you look careful into the package.json history you might spot that i bumped the minimum required nodejs version to v0.8.x :)
if you install this specific version and try to build the webclient you might notice that it dies. in fact the coffee compiler dies and spits out an error message, saying that there is a missing escape character. the very same one that this pull request is trying to eliminate.

so i think it's ok not to merge it. what do you think?

**Comment by lloydwatkin** [comment]
I'll try this now and let you know @dodo as a confirmation :)

**Comment by dodo** [comment]
you can still use node 0.6 with this patch, but it will die on watching files.

**Comment by lloydwatkin** [comment]
It's building fine with node v0.8.0 so you are right - not that there's a doubt. Must have missed the announcement about moving to 0.8.0 apologies :)

**Comment by dodo** [comment]
i assumed you would be watching the commits :D

it's quite easy: nearly every time package.json is touched something changed, that requires an update.

**Comment by lloydwatkin** [comment]
Yeah sorry I've been working on server and java server recently :)

**Comment by lloydwatkin** [comment]
I'll bear that thought in mind in the future

**Comment by dodo** [comment]
and i'll update the team channel next time :)

**Pull request closed without merging**
