### PR TITLE
Plugin

### PR DESCRIPTION
**Pull request by lloydwatkin**
Continues https://github.com/buddycloud/buddycloud-webclient/pull/113#issuecomment-6972906

### CODE REVIEW

**Comment by lloydwatkin** [comment]
I think we've stabilised the plugin setup (between @dodo and myself) so if the team are happy this can be merged :)

**Comment by dodo** [comment]
github#fail™

this cannot be merged since i already merged the changes from `strophe.buddycloud.js`.

**Comment by lloydwatkin** [comment]
Ok, do you want me to merge the latest master and create a new pull request again?

**Comment by dodo** [comment]
no, the plugin api is ready .. you just have to update your side i guess.

the thing is i'll never approve a plugin api where you have to run the build process every time (that would be against the definition of a plugin right?).

please at least try once my approach and you will see its even easier to use. and you can use your own folder and fill it with all the pictures and other files you want.

**Comment by lloydwatkin** [comment]
Hey @dodo,

This pull request doesn't require that you rebuild the server. You simply drop files in place and edit config and it works. I incorporated your Modernizer changes. The one addition in packaging.coffee is there so if you have put plugins in place whilst developing against the server these are included in the build.tar.gz, and not because the server needs to be built with them in. Hopefully we just had some confusion there and that clears it up? :)

**Comment by dodo** [comment]
sorry,  i shouldn't comment before my first mate tea.

so, you want that the server is able to put the plugins into the tarball?

**Comment by lloydwatkin** [comment]
I think it makes sense. For example, I write a plugin that works with the latest code and then tar up to deploy, it would be nice if the plugins went with it. Otherwise my deploy would be multiple steps. Its not essential just a nice to have :)

I have no problem if you do not wish to include that additional bit of code, makes my life easier, might save other devs some time too? But who knows ;)

**Comment by dodo** [comment]
no, i understand now.

and i understand that's this might be something that saves alot of time for a alot of developers in the future, but i also would like to have it in a way which isn't only your way, or only my way.

so my idea is that i would like to put the build server urls for the plugins inside the config.js (the one from the build server :P (i should rename that one)). what do you think?

(besides, this is the only _new_ change, since the other regarding strophe.bc is already merged in.)

**Comment by lloydwatkin** [comment]
Does this mean that you would code the paths of the plugins you wanted to build into the webclient in the root config.js? Would this then lead to having to edit two configs when developing? (this doesn't mean to say I disagree but I think its good to play devil's advocate).

With regards to the location of plugins I think we need to define a standard location for them, otherwise people will place where-ever they want and things might not work in that location (e.g. because of relative paths, publicly accessible files, etc). I also understand that you are best placed to decide where this should be :)

I have added you on my work skype account in case you want to chat. I think many of the misunderstandings have come from the method of communication rather than us disagreeing on things ;)

**Pull request closed without merging**
