### PR TITLE
I hate these (anon) avatars

### PR DESCRIPTION
**Pull request by lloydwatkin**
Hate is a strong word, but I _hate_ these generic avatars for everyone that doesn't have an avatar on the media server. So I've coded up a fallback to gravatar.....

Also fixed it so if the user doesn't have config.api_service set the webclient doesn't fail to load

Finally, replaced all mentions of gravatar with avatar

### CODE REVIEW

**Comment by rodrigods** [comment]
+1

**Comment by lloydwatkin** [comment]
Why close the pull request @rodrigods  ?

**Comment by rodrigods** [comment]
sorry, clicked on the wrong button =) just wanted to +1 in the request

**Comment by lloydwatkin** [comment]
No worries :)

**Comment by ghost** [comment]
ALL HAIL LLOYD.

_sigh_

2012/9/4 The Travis Bot notifications@github.com

> This pull request passeshttp://travis-ci.org/buddycloud/buddycloud-webclient/builds/2336592(merged
> d450562https://github.com/buddycloud/buddycloud-webclient/commit/d450562finto
> 0a2a21bhttps://github.com/buddycloud/buddycloud-webclient/commit/0a2a21b8
> ).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/buddycloud/buddycloud-webclient/pull/136#issuecomment-8278955.

http://xing.to/IMuentzenberger
https://www.xing.com/go/invite/6498355.27c10b

**Pull request merged**
