### PR TITLE
Update to the webclient to support plugins

### PR DESCRIPTION
**Pull request by lloydwatkin**
Most recent merge of plugin system with buddycloud webclient master.

All changes are backwards compatable and do not effect current functionality. 

Will try and put together a few more plugins to demonstrate the usefulness as and when I have time.

### CODE REVIEW

**Comment by dodo** [comment]
i still don't know what's so useful when i have to rebuild the webclient every time i wanna add a plugin?
please enlighten me …

**Comment by lloydwatkin** [comment]
@dodo Have replied via dodo@buddycloud.org

**Comment by dodo** [comment]
sorry, i pushed some commits that broke this pull request. :P
would you mind sending a new pull request with the changes from `src/vendor/strophe.buddycloud.js`?
i think the other changes are not needed anymore.

**Comment by lloydwatkin** [comment]
will get this done tonight and make pull request
On Jul 13, 2012 7:11 PM, "▟ ▖▟ ▖" <
reply@reply.github.com>
wrote:

**Comment by dodo** [comment]
awesome! thank you very much.

**Comment by lloydwatkin** [comment]
See https://github.com/buddycloud/buddycloud-webclient/pull/114

**Pull request closed without merging**
